[package]
name = "mo_core"
edition = "2024"
version.workspace = true

[dependencies]
chrono = { version = "0.4.45", features = ["serde"] }
rusqlite = { version = "0.40.1", features = ["bundled"] }
serde.workspace = true
serde_json.workspace = true
tempfile = "3.27.0"
thiserror.workspace = true
uuid = { version = "1.24.0", features = ["v4"] }
