[package]
name = "mo_worker"
edition = "2024"
version.workspace = true

[dependencies]
anyhow.workspace = true
chrono = "0.4.45"
futures-util.workspace = true
mo_core = { version = "0.1.0", path = "../mo_core" }
nah_chat = { version = "0.7.0", git = "https://github.com/linmx0130/nah" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
uuid = { version = "1.24.0", features = ["v4"] }

[dev-dependencies]
axum = "0.8.9"
serde_json.workspace = true
tempfile = "3.27.0"
tokio.workspace = true
